name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # 只要 main 分支有 push 就會自動部署

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 如果有 package.json，這兩步驟請保留，否則可刪除
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: lunchorder-2b476
          channelId: live